/*
 * Kalahar, M. (2025). CIS 530 Intermediate Java Programming. Bellevue University.
 */
package com.bookclub.model;

import org.springframework.data.annotation.Id;

import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;

/**
 * Represents a "Book of the Month" entry, linking an ISBN to a specific month.
 * This class is typically used to feature a book for a particular month in the book club.
 */
public class BookOfTheMonth {

    @Id
    private String id;
    @NotNull
    @NotEmpty(message = "ISBN is a required field.")
    private String isbn;

    private Integer month;

    /**
     * Gets the ISBN of the featured book.
     *
     * @return The ISBN of the book.
     */
    public String getIsbn() {
        return isbn;
    }

     /**
     * Sets the ISBN of the featured book.
     *
     * @param isbn The ISBN to set.
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * Gets the month for which this book is featured.
     * The month is represented as an integer (e.g., 1 for January, 12 for December).
     *
     * @return The month as an Integer.
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * Sets the month for which this book is featured.
     *
     * @param month The month to set, represented as an Integer.
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

     /**
     * Gets the unique identifier for this BookOfTheMonth entry.
     * This is typically auto-generated by the database.
     *
     * @return The unique ID of the entry.
     */
    public String getId() {
        return id;
    }

     /**
     * Sets the unique identifier for this BookOfTheMonth entry.
     *
     * @param id The unique ID to set.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Returns a string representation of the BookOfTheMonth object.
     * This includes the id, isbn, and month.
     *
     * @return A string representation of the BookOfTheMonth object.
     */
    @Override
    public String toString() {
        return "BookOfTheMonth{id='" + id + '\'' +
                ", isbn='" + isbn + '\'' +
                ", month='" + month + '\'' +
                '}';
    }
}
